# Generated by Django 3.0.4 on 2020-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('JSON', 'JSON'), ('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('C++', 'C++'), ('C', 'C')], max_length=100),
        ),
    ]
